"""End-to-end integration tests for the full invoice processing pipeline.

Strategy:
  - Real SQLite in-memory DB and real ORM
  - Real PDF fixture generated by fpdf2
  - Real extraction (pdfplumber), classification, validation, export
  - Only the LLM backend is mocked (returns deterministic JSON)
  - Pipeline driven via process_invoice() — the v3 entry point
"""
from __future__ import annotations

import json
import tempfile
from datetime import date
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from src.agent.pipeline import (
    PipelineComponents,
    export_file,
    post_journal,
    process_invoice,
    recover_interrupted,
    re_enqueue_received,
)
from src.classification.accounting_coder import AccountingCoder
from src.classification.classifier import Classifier
from src.cost_catalog.catalog import CostCatalog
from src.extraction.hybrid_extractor import HybridExtractor
from src.extraction.llm_extractor import LLMBackendBase, LLMExtractor
from src.extraction.ocr_engine import TesseractEngine
from src.extraction.ocr_preprocessor import OCRPreprocessor
from src.extraction.pdf_reader import PDFReader
from src.accounting.entry_generator import EntryGenerator
from src.accounting.journal_store import JournalRepository
from src.agent.auto_corrector import AutoCorrector
from src.models.enums import ExtractionMethod, FlagType, InvoiceDirection, InvoiceStatus
from src.models.invoice import ConfidenceField, InvoiceRecord
from src.storage.db import build_engine, build_session_factory, init_db
from src.storage.exporters.json_exporter import JSONExporter
from src.storage.repository import InvoiceRepository
from src.suivi.aggregator import Aggregator
from src.suivi.reconciler import Reconciler
from src.utils.file_utils import sha256
from src.validation.anomaly_detector import AnomalyDetector
from src.validation.coherence_checker import CoherenceChecker
from src.validation.duplicate_detector import DuplicateDetector
from src.validation.field_validator import FieldValidator

from tests.fixtures.make_invoice_pdf import make_client_invoice_pdf, make_supplier_invoice_pdf


# ── Shared config ─────────────────────────────────────────────────────────────

_CONFIG = {
    "ingestion": {
        "watch_path": "./inbox",
        "processed_path": "./processed",
        "supported_formats": ["pdf", "png", "jpg"],
        "poll_interval_seconds": 1,
    },
    "extraction": {
        "languages": ["fr"],
        "render_dpi": 150,
        "min_native_pdf_chars": 20,
        "min_text_quality_ratio": 0.7,
        "confidence_thresholds": {
            "minimum_confidence": 0.5,
            "warning_confidence": 0.7,
        },
    },
    "classification": {
        "rules_file": "config/rules/classification_rules.yaml",
    },
    "validation": {
        "math_tolerance_absolute": 0.02,
        "math_tolerance_relative": 0.001,
        "tva_rates_allowed": [0, 7, 13, 19],
        "duplicate_window_days": 90,
        "high_value_threshold": 50000,
        "warning_escalation_threshold": 2,
    },
    "storage": {
        "db_url": "sqlite:///:memory:",
        "export_format": "json",
        "export_path": "",  # set per-test in tmpdir
    },
    "agent": {
        "max_retry_attempts": 2,
        "log_level": "WARNING",
    },
    "correction": {
        "math_confidence_ratio_threshold": 0.75,
        "math_corrected_confidence": 0.95,
        "ai_corrected_confidence": 0.90,
    },
    "currency": {"default": "TND"},
}

_CLASSIFICATION_RULES = [
    {
        "name": "biat_it_as_recipient",
        "condition": {"field": "recipient_tax_id", "matches": r"^9876543"},
        "result": "SUPPLIER",
    },
    {
        "name": "biat_it_as_issuer",
        "condition": {"field": "issuer_tax_id", "matches": r"^9876543"},
        "result": "CLIENT",
    },
    {"name": "default", "result": "UNKNOWN"},
]


# ── Deterministic LLM response for supplier invoice ───────────────────────────

_SUPPLIER_LLM_RESPONSE = json.dumps({
    "issuer_name": {"value": "Acme Solutions SARL", "confidence": 0.95, "source": "Acme Solutions SARL"},
    "issuer_tax_id": {"value": "1234567A/M/P/000", "confidence": 0.92, "source": "1234567A/M/P/000"},
    "recipient_name": {"value": "BIAT IT", "confidence": 0.95, "source": "BIAT IT"},
    "recipient_tax_id": {"value": "9876543B/N/Q/001", "confidence": 0.90, "source": "9876543B/N/Q/001"},
    "invoice_number": {"value": "INV-2024-TEST-001", "confidence": 0.98, "source": "INV-2024-TEST-001"},
    "invoice_date": {"value": "2024-03-15", "confidence": 0.95, "source": "15/03/2024"},
    "due_date": {"value": "2024-04-15", "confidence": 0.90, "source": "15/04/2024"},
    "amount_ht": {"value": 1500.0, "confidence": 0.95, "source": "1500.00"},
    "tva_rate": {"value": 19.0, "confidence": 0.95, "source": "19%"},
    "tva_amount": {"value": 285.0, "confidence": 0.95, "source": "285.00"},
    "amount_ttc": {"value": 1785.0, "confidence": 0.95, "source": "1785.00"},
    "currency": {"value": "TND", "confidence": 1.0, "source": "TND"},
    "line_items": [
        {"description": "Licence logiciel ERP annuelle", "quantity": 1.0, "unit_price": 1000.0, "line_total": 1000.0, "tva_rate": 19.0},
        {"description": "Support et maintenance", "quantity": 1.0, "unit_price": 500.0, "line_total": 500.0, "tva_rate": 19.0},
    ],
})

_CLIENT_LLM_RESPONSE = json.dumps({
    "issuer_name": {"value": "BIAT IT", "confidence": 0.95, "source": "BIAT IT"},
    "issuer_tax_id": {"value": "9876543B/N/Q/001", "confidence": 0.92, "source": "9876543B/N/Q/001"},
    "recipient_name": {"value": "Tech Corp Tunisia", "confidence": 0.90, "source": "Tech Corp Tunisia"},
    "recipient_tax_id": {"value": "5556667C/M/P/002", "confidence": 0.85, "source": "5556667C/M/P/002"},
    "invoice_number": {"value": "CLI-2024-001", "confidence": 0.98, "source": "CLI-2024-001"},
    "invoice_date": {"value": "2024-03-20", "confidence": 0.95, "source": "20/03/2024"},
    "due_date": {"value": None, "confidence": 0.0, "source": None},
    "amount_ht": {"value": 3000.0, "confidence": 0.95, "source": "3000.00"},
    "tva_rate": {"value": 19.0, "confidence": 0.95, "source": "19%"},
    "tva_amount": {"value": 570.0, "confidence": 0.95, "source": "570.00"},
    "amount_ttc": {"value": 3570.0, "confidence": 0.95, "source": "3570.00"},
    "currency": {"value": "TND", "confidence": 1.0, "source": "TND"},
    "line_items": [
        {"description": "Prestation de service informatique", "quantity": 1.0, "unit_price": 3000.0, "line_total": 3000.0, "tva_rate": 19.0},
    ],
})


# ── Fixtures ──────────────────────────────────────────────────────────────────

@pytest.fixture()
def tmp_dirs(tmp_path):
    (tmp_path / "inbox").mkdir()
    (tmp_path / "processed").mkdir()
    (tmp_path / "exports").mkdir()
    return tmp_path


@pytest.fixture()
def db_session():
    engine = build_engine("sqlite:///:memory:")
    init_db(engine)
    SessionFactory = build_session_factory(engine)
    session = SessionFactory()
    yield session
    session.close()
    engine.dispose()


@pytest.fixture()
def repository(db_session):
    return InvoiceRepository(db_session)


def _build_components(repository, export_path: str, llm_response: str) -> PipelineComponents:
    """Build PipelineComponents with a mocked LLM backend."""
    cfg = dict(_CONFIG)
    cfg["storage"] = dict(cfg["storage"], export_path=export_path)

    class _MockBackend(LLMBackendBase):
        def complete(self, system: str, user: str) -> str:
            return llm_response

    extractor = HybridExtractor(
        pdf_reader=PDFReader(
            min_chars=cfg["extraction"]["min_native_pdf_chars"],
            min_quality_ratio=cfg["extraction"]["min_text_quality_ratio"],
        ),
        preprocessor=OCRPreprocessor(),
        ocr_engine=TesseractEngine(languages=["fr"]),
        llm_extractor=LLMExtractor(
            backend=_MockBackend(),
            languages=cfg["extraction"]["languages"],
            mode="full_schema",   # mock returns full schema; production uses amounts_only
        ),
        config=cfg,
    )

    catalog = CostCatalog.from_yaml("config/cost_catalog.yaml")
    journal_repository = JournalRepository(repository.session)

    return PipelineComponents(
        extractor=extractor,
        classifier=Classifier(rules=_CLASSIFICATION_RULES),
        coder=AccountingCoder(catalog=catalog),
        field_validator=FieldValidator(
            confidence_thresholds=cfg["extraction"]["confidence_thresholds"]
        ),
        coherence_checker=CoherenceChecker(config=cfg),
        duplicate_detector=DuplicateDetector(config=cfg, repository=repository),
        anomaly_detector=AnomalyDetector(config=cfg, repository=repository),
        auto_corrector=AutoCorrector(config=cfg, repository=repository),
        exporter=JSONExporter(export_path=export_path),
        entry_generator=EntryGenerator(),
        cost_catalog=catalog,
        repository=repository,
        journal_repository=journal_repository,
        max_retries=cfg["agent"]["max_retry_attempts"],
    )


def _make_invoice_record(file_path: Path) -> InvoiceRecord:
    return InvoiceRecord(
        file_hash=sha256(str(file_path)),
        raw_file_path=str(file_path),
        status=InvoiceStatus.RECEIVED,
    )


# ── Supplier invoice E2E ──────────────────────────────────────────────────────

class TestSupplierInvoicePipeline:

    def test_supplier_invoice_reaches_validated_or_flagged(self, tmp_dirs, repository):
        pdf_path = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "supplier_001.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        saved = repository.get_by_id(invoice.id)
        assert saved.status in (InvoiceStatus.VALIDATED, InvoiceStatus.JOURNALED, InvoiceStatus.EXPORTED, InvoiceStatus.FLAGGED)

    def test_supplier_invoice_direction_classified(self, tmp_dirs, repository):
        pdf_path = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "supplier_002.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        saved = repository.get_by_id(invoice.id)
        assert saved.direction == InvoiceDirection.SUPPLIER

    def test_supplier_invoice_amounts_extracted(self, tmp_dirs, repository):
        pdf_path = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "supplier_003.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        saved = repository.get_by_id(invoice.id)
        assert saved.amount_ttc.value == pytest.approx(1785.0)
        assert saved.amount_ht.value == pytest.approx(1500.0)
        assert saved.tva_amount.value == pytest.approx(285.0)

    def test_supplier_invoice_dates_parsed(self, tmp_dirs, repository):
        pdf_path = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "supplier_004.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        saved = repository.get_by_id(invoice.id)
        assert saved.invoice_date.value == date(2024, 3, 15)
        assert saved.due_date.value == date(2024, 4, 15)

    def test_supplier_invoice_accounting_code_assigned(self, tmp_dirs, repository):
        pdf_path = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "supplier_005.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        saved = repository.get_by_id(invoice.id)
        # "Licence logiciel ERP" → licences_saas (compte 6133) or logiciels_acquis (2284)
        assert saved.accounting_compte is not None

    def test_supplier_invoice_line_items_stored(self, tmp_dirs, repository):
        pdf_path = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "supplier_006.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        saved = repository.get_by_id(invoice.id)
        assert len(saved.line_items) == 2
        descriptions = [li.description for li in saved.line_items]
        assert any("logiciel" in (d or "").lower() for d in descriptions)

    def test_supplier_invoice_extraction_method_set(self, tmp_dirs, repository):
        pdf_path = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "supplier_007.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        saved = repository.get_by_id(invoice.id)
        assert saved.extraction_method is not None

    def test_supplier_invoice_export_file_created(self, tmp_dirs, repository):
        pdf_path = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "supplier_008.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        export_files = list((tmp_dirs / "exports").glob("*.json"))
        assert len(export_files) == 1
        exported = json.loads(export_files[0].read_text())
        assert exported["id"] == str(invoice.id)

    def test_supplier_invoice_status_history_written(self, tmp_dirs, repository):
        """Every status transition is recorded in the audit trail."""
        from src.storage.orm_models import StatusHistoryORM
        from sqlalchemy import select as sa_select

        pdf_path = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "supplier_009.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        history = repository.session.execute(
            sa_select(StatusHistoryORM).where(
                StatusHistoryORM.invoice_id == invoice.id
            ).order_by(StatusHistoryORM.changed_at)
        ).scalars().all()

        statuses = [h.to_status for h in history]
        assert "EXTRACTING" in statuses
        assert "EXTRACTED" in statuses
        assert "CLASSIFYING" in statuses


# ── Client invoice E2E ────────────────────────────────────────────────────────

class TestClientInvoicePipeline:

    def test_client_invoice_direction_classified(self, tmp_dirs, repository):
        pdf_path = make_client_invoice_pdf(tmp_dirs / "inbox" / "client_001.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _CLIENT_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        saved = repository.get_by_id(invoice.id)
        assert saved.direction == InvoiceDirection.CLIENT

    def test_client_invoice_accounting_code_assigned(self, tmp_dirs, repository):
        pdf_path = make_client_invoice_pdf(tmp_dirs / "inbox" / "client_002.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _CLIENT_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        saved = repository.get_by_id(invoice.id)
        assert saved.accounting_compte is not None

    def test_client_invoice_ttc_extracted(self, tmp_dirs, repository):
        pdf_path = make_client_invoice_pdf(tmp_dirs / "inbox" / "client_003.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _CLIENT_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        saved = repository.get_by_id(invoice.id)
        assert saved.amount_ttc.value == pytest.approx(3570.0)


# ── Duplicate detection E2E ───────────────────────────────────────────────────

class TestDuplicateDetectionE2E:

    def test_second_identical_invoice_flagged_as_duplicate(self, tmp_dirs, repository):
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        # First invoice goes through fine
        pdf1 = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "dup_first.pdf")
        inv1 = _make_invoice_record(pdf1)
        repository.save(inv1)
        process_invoice(inv1, components)
        saved1 = repository.get_by_id(inv1.id)
        first_status = saved1.status

        # Second invoice with same number from same issuer
        pdf2 = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "dup_second.pdf")
        inv2 = InvoiceRecord(
            file_hash=sha256(str(pdf2)) + "_alt",  # different hash (different file)
            raw_file_path=str(pdf2),
            status=InvoiceStatus.RECEIVED,
        )
        repository.save(inv2)
        process_invoice(inv2, components)
        saved2 = repository.get_by_id(inv2.id)

        # Must be flagged (FLAGGED or ERROR) due to duplicate detection
        flag_types = [f.flag_type for f in saved2.flags]
        assert FlagType.DUPLICATE in flag_types
        assert saved2.status in (InvoiceStatus.FLAGGED, InvoiceStatus.ERROR)


# ── Lifecycle & reconciliation E2E ────────────────────────────────────────────

class TestLifecycleE2E:

    def test_mark_paid_advances_supplier_invoice(self, tmp_dirs, repository):
        pdf_path = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "pay_001.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        saved = repository.get_by_id(invoice.id)
        if saved.status not in (InvoiceStatus.EXPORTED, InvoiceStatus.VALIDATED):
            pytest.skip(f"Invoice in unexpected status {saved.status} — check validation flags")

        # Manually move to EXPORTED for this test
        saved.status = InvoiceStatus.EXPORTED
        repository.save(saved)

        from src.suivi.lifecycle_tracker import LifecycleTracker
        tracker = LifecycleTracker(repository=repository)
        paid = tracker.mark_paid(
            invoice_id=invoice.id,
            payment_reference="VIR-2024-001",
            amount=1785.0,
        )

        assert paid.status == InvoiceStatus.PAID
        assert paid.paid_at is not None

        db_paid = repository.get_by_id(invoice.id)
        assert db_paid.status == InvoiceStatus.PAID

    def test_aggregator_snapshot_reflects_pipeline_state(self, tmp_dirs, repository):
        pdf_path = make_supplier_invoice_pdf(tmp_dirs / "inbox" / "agg_001.pdf")
        components = _build_components(repository, str(tmp_dirs / "exports"), _SUPPLIER_LLM_RESPONSE)

        invoice = _make_invoice_record(pdf_path)
        repository.save(invoice)
        process_invoice(invoice, components)

        agg = Aggregator(repository=repository)
        snap = agg.snapshot()

        total_invoices = sum(snap.invoices_by_status.values())
        assert total_invoices >= 1


# ── Recovery E2E ─────────────────────────────────────────────────────────────

class TestRecoveryE2E:

    def test_recovery_resets_mid_flight_invoices(self, tmp_dirs, repository):
        """Invoices stuck in EXTRACTING are reset to RECEIVED on agent startup."""
        stuck = InvoiceRecord(
            file_hash="stuck_hash",
            raw_file_path="/tmp/stuck.pdf",
            status=InvoiceStatus.EXTRACTING,
        )
        repository.save(stuck)

        recover_interrupted(repository)

        recovered = repository.get_by_id(stuck.id)
        assert recovered.status == InvoiceStatus.RECEIVED

    def test_recovery_re_enqueues_received_invoices(self, tmp_dirs, repository):
        received = InvoiceRecord(
            file_hash="received_hash",
            raw_file_path="/tmp/received.pdf",
            status=InvoiceStatus.RECEIVED,
        )
        repository.save(received)

        mock_ingestor = MagicMock()
        re_enqueue_received(repository, mock_ingestor)

        mock_ingestor.enqueue.assert_called_once()
        args = mock_ingestor.enqueue.call_args[0]
        assert args[0].id == received.id
