"""bct_compliance_fields_and_audit_log

Revision ID: 8b8980897ba0
Revises: e3cd7136c2f3
Create Date: 2026-06-28 15:35:13.777432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8980897ba0'
down_revision: Union[str, Sequence[str], None] = 'e3cd7136c2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    with op.batch_alter_table('client_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=False, server_default='TND'))
        batch_op.add_column(sa.Column('is_export', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('domiciliation_bank', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('domiciliation_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('shipment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('repatriation_deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('repatriation_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('payment_guarantee_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('foreign_currency_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_invoices', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('foreign_currency_amount')
        batch_op.drop_column('payment_guarantee_type')
        batch_op.drop_column('repatriation_date')
        batch_op.drop_column('repatriation_deadline')
        batch_op.drop_column('shipment_date')
        batch_op.drop_column('domiciliation_number')
        batch_op.drop_column('domiciliation_bank')
        batch_op.drop_column('is_export')
        batch_op.drop_column('currency')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
