"""initial_schema

Revision ID: e3cd7136c2f3
Revises: 
Create Date: 2026-06-28 15:26:06.341891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cd7136c2f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('designation', sa.Text(), nullable=False),
    sa.Column('compte_immobilisation', sa.String(length=16), nullable=False),
    sa.Column('compte_amortissement', sa.String(length=16), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=False),
    sa.Column('acquisition_cost_ht', sa.Float(), nullable=False),
    sa.Column('useful_life_years', sa.Integer(), nullable=False),
    sa.Column('depreciation_method', sa.String(length=16), nullable=False),
    sa.Column('supplier_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('fully_depreciated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index('idx_assets_active', ['fully_depreciated'], unique=False)
        batch_op.create_index('idx_assets_compte', ['compte_immobilisation'], unique=False)

    op.create_table('chartes_projet',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('client', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('budget_jh', sa.Float(), nullable=False),
    sa.Column('taux_jh', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chartes_projet', schema=None) as batch_op:
        batch_op.create_index('idx_chartes_active', ['is_active'], unique=False)
        batch_op.create_index('idx_chartes_project_id', ['project_id'], unique=False)

    op.create_table('client_invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('issuer_name', sa.Text(), nullable=False),
    sa.Column('issuer_tax_id', sa.String(length=32), nullable=False),
    sa.Column('issuer_address', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('client_tax_id', sa.String(length=32), nullable=False),
    sa.Column('client_address', sa.Text(), nullable=True),
    sa.Column('amount_ht', sa.Float(), nullable=False),
    sa.Column('tva_amount', sa.Float(), nullable=False),
    sa.Column('amount_ttc', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_template_id', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_invoices_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_invoices_invoice_date'), ['invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_invoices_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_client_invoices_status'), ['status'], unique=False)

    op.create_table('feuilles_de_route',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titre', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('projet_id', sa.String(length=64), nullable=True),
    sa.Column('responsable_id', sa.String(length=64), nullable=True),
    sa.Column('statut', sa.String(length=16), nullable=False),
    sa.Column('priorite', sa.String(length=8), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiches_mensuelles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('prepared_by', sa.String(length=128), nullable=False),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_year', 'period_month', 'prepared_by', name='uq_fiche_period_preparer')
    )
    with op.batch_alter_table('fiches_mensuelles', schema=None) as batch_op:
        batch_op.create_index('idx_fiches_period', ['period_year', 'period_month'], unique=False)
        batch_op.create_index('idx_fiches_status', ['status'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_file_path', sa.Text(), nullable=False),
    sa.Column('file_mime_type', sa.String(length=64), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('extraction_method', sa.String(length=32), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('issuer_name', sa.Text(), nullable=True),
    sa.Column('issuer_name_conf', sa.Float(), nullable=True),
    sa.Column('issuer_tax_id', sa.Text(), nullable=True),
    sa.Column('issuer_tax_id_conf', sa.Float(), nullable=True),
    sa.Column('recipient_name', sa.Text(), nullable=True),
    sa.Column('recipient_name_conf', sa.Float(), nullable=True),
    sa.Column('recipient_tax_id', sa.Text(), nullable=True),
    sa.Column('recipient_tax_id_conf', sa.Float(), nullable=True),
    sa.Column('invoice_number', sa.Text(), nullable=True),
    sa.Column('invoice_number_conf', sa.Float(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('invoice_date_conf', sa.Float(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_date_conf', sa.Float(), nullable=True),
    sa.Column('amount_ht', sa.Float(), nullable=True),
    sa.Column('amount_ht_conf', sa.Float(), nullable=True),
    sa.Column('tva_rate', sa.Float(), nullable=True),
    sa.Column('tva_rate_conf', sa.Float(), nullable=True),
    sa.Column('tva_amount', sa.Float(), nullable=True),
    sa.Column('tva_amount_conf', sa.Float(), nullable=True),
    sa.Column('amount_ttc', sa.Float(), nullable=True),
    sa.Column('amount_ttc_conf', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_extracted_json', sa.JSON(), nullable=True),
    sa.Column('cost_catalog_id', sa.Text(), nullable=True),
    sa.Column('accounting_compte', sa.String(length=16), nullable=True),
    sa.Column('accounting_label', sa.Text(), nullable=True),
    sa.Column('charge_nature', sa.String(length=16), nullable=True),
    sa.Column('charge_type', sa.String(length=8), nullable=True),
    sa.Column('matched_po_id', sa.Text(), nullable=True),
    sa.Column('matched_contract_id', sa.Text(), nullable=True),
    sa.Column('matched_client_id', sa.Text(), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('human_review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('export_reference', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('idx_invoices_direction_status', ['direction', 'status'], unique=False)
        batch_op.create_index('idx_invoices_due_date', ['due_date'], unique=False)
        batch_op.create_index('idx_invoices_dup_detection', ['issuer_tax_id', 'invoice_number', 'amount_ttc'], unique=False)
        batch_op.create_index('idx_invoices_invoice_number', ['invoice_number'], unique=False)
        batch_op.create_index('idx_invoices_status', ['status'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=128), nullable=False),
    sa.Column('date_ecriture', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_invoice_id', sa.Uuid(), nullable=True),
    sa.Column('source_asset_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index('idx_journal_date', ['date_ecriture'], unique=False)
        batch_op.create_index('idx_journal_invoice', ['source_invoice_id'], unique=False)
        batch_op.create_index('idx_journal_reference', ['reference'], unique=False)

    op.create_table('lignes_budget',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('projet_id', sa.String(length=64), nullable=False),
    sa.Column('categorie', sa.String(length=128), nullable=False),
    sa.Column('montant_prevu', sa.Float(), nullable=False),
    sa.Column('montant_consomme', sa.Float(), nullable=False),
    sa.Column('devise', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lignes_budget', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lignes_budget_projet_id'), ['projet_id'], unique=False)

    op.create_table('phases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('planned_jh', sa.Float(), nullable=False),
    sa.Column('consumed_jh', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('livrables', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.create_index('idx_phases_project_id', ['project_id'], unique=False)
        batch_op.create_index('idx_phases_project_status', ['project_id', 'status'], unique=False)
        batch_op.create_index('idx_phases_status', ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nom', sa.String(length=64), nullable=False),
    sa.Column('prenom', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('departement', sa.String(length=64), nullable=False),
    sa.Column('is_first_login', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('asset_project_links',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('allocation_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'project_id')
    )
    with op.batch_alter_table('asset_project_links', schema=None) as batch_op:
        batch_op.create_index('idx_apl_asset_id', ['asset_id'], unique=False)
        batch_op.create_index('idx_apl_project_id', ['project_id'], unique=False)

    op.create_table('avances_programmees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fiche_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('charte_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('montant_ht', sa.Float(), nullable=False),
    sa.Column('schedule_reference', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['fiche_id'], ['fiches_mensuelles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avances_programmees', schema=None) as batch_op:
        batch_op.create_index('idx_avances_fiche_id', ['fiche_id'], unique=False)
        batch_op.create_index('idx_avances_project_id', ['project_id'], unique=False)

    op.create_table('client_line_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('tva_rate', sa.Float(), nullable=False),
    sa.Column('tva_amount', sa.Float(), nullable=False),
    sa.Column('compte_produit', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['client_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiche_phases',
    sa.Column('fiche_id', sa.String(length=64), nullable=False),
    sa.Column('phase_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['fiche_id'], ['fiches_mensuelles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fiche_id', 'phase_id')
    )
    op.create_table('journal_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('compte', sa.String(length=16), nullable=False),
    sa.Column('libelle', sa.Text(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.Column('tva_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livrables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phase_id', sa.String(length=64), nullable=False),
    sa.Column('titre', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date_livraison_prevue', sa.Date(), nullable=False),
    sa.Column('date_livraison_reelle', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=16), nullable=False),
    sa.Column('fichier_path', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('livrables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_livrables_phase_id'), ['phase_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_reference', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_flags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('flag_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_flags')
    op.drop_table('status_history')
    op.drop_table('payments')
    op.drop_table('notifications')
    with op.batch_alter_table('livrables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_livrables_phase_id'))

    op.drop_table('livrables')
    op.drop_table('line_items')
    op.drop_table('journal_lines')
    op.drop_table('fiche_phases')
    op.drop_table('client_line_items')
    with op.batch_alter_table('avances_programmees', schema=None) as batch_op:
        batch_op.drop_index('idx_avances_project_id')
        batch_op.drop_index('idx_avances_fiche_id')

    op.drop_table('avances_programmees')
    with op.batch_alter_table('asset_project_links', schema=None) as batch_op:
        batch_op.drop_index('idx_apl_project_id')
        batch_op.drop_index('idx_apl_asset_id')

    op.drop_table('asset_project_links')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('phases', schema=None) as batch_op:
        batch_op.drop_index('idx_phases_status')
        batch_op.drop_index('idx_phases_project_status')
        batch_op.drop_index('idx_phases_project_id')

    op.drop_table('phases')
    with op.batch_alter_table('lignes_budget', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lignes_budget_projet_id'))

    op.drop_table('lignes_budget')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_journal_reference')
        batch_op.drop_index('idx_journal_invoice')
        batch_op.drop_index('idx_journal_date')

    op.drop_table('journal_entries')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('idx_invoices_status')
        batch_op.drop_index('idx_invoices_invoice_number')
        batch_op.drop_index('idx_invoices_dup_detection')
        batch_op.drop_index('idx_invoices_due_date')
        batch_op.drop_index('idx_invoices_direction_status')

    op.drop_table('invoices')
    with op.batch_alter_table('fiches_mensuelles', schema=None) as batch_op:
        batch_op.drop_index('idx_fiches_status')
        batch_op.drop_index('idx_fiches_period')

    op.drop_table('fiches_mensuelles')
    op.drop_table('feuilles_de_route')
    with op.batch_alter_table('client_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_client_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_client_invoices_invoice_date'))
        batch_op.drop_index(batch_op.f('ix_client_invoices_client_id'))

    op.drop_table('client_invoices')
    with op.batch_alter_table('chartes_projet', schema=None) as batch_op:
        batch_op.drop_index('idx_chartes_project_id')
        batch_op.drop_index('idx_chartes_active')

    op.drop_table('chartes_projet')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index('idx_assets_compte')
        batch_op.drop_index('idx_assets_active')

    op.drop_table('assets')
    # ### end Alembic commands ###
