"""add invoice_number to fiches_mensuelles

Revision ID: ece2bf29445f
Revises: 9e32aa144819
Create Date: 2026-06-12 10:22:05.610238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece2bf29445f'
down_revision: Union[str, Sequence[str], None] = '9e32aa144819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiches_mensuelles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiches_mensuelles', schema=None) as batch_op:
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
