#!/usr/bin/env python3
"""Reset MongoDB + local upload/email artifacts back to a clean demo state,
then re-run the demo seeders in order.

Unlike seed_demo.py / seed_budget_actuals.py / seed_projects.py /
seed_risks.py / seed_roadmap.py (all idempotent upsert-or-skip, never
destructive — see their own docstrings), this script IS destructive: it
clears every Mongo collection those seeders own before reseeding. It
never touches users, audit_logs, sessions/tokens, notifications, or
payments — those aren't demo-seeded content and wiping them would break
login / the audit trail / anything you were testing manually.

Usage:
    python scripts/reset_demo.py --dry-run   # show what would be cleared, no writes
    python scripts/reset_demo.py --yes       # actually reset + reseed

Requires --yes (no default destructive action) — this is meant to be run
deliberately before a demo/rehearsal, not accidentally.
"""
from __future__ import annotations

import argparse
import asyncio
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))
sys.path.insert(0, str(ROOT))

# api.auth must be imported first (before src.storage.mongodb) — it's what
# loads .env (MONGODB_URI included), which mongodb.py reads as a module-level
# constant at import time.
import api.auth  # noqa: F401
from src.storage.mongodb import close_mongodb, init_beanie
from src.storage.sync_mongo_repository import _get_db

# Collections written by the demo seeders — everything here is regenerated
# by the reseed step below. Deliberately excludes: users, audit_logs,
# active_tokens, revoked_tokens, password_verifications, payments,
# payment_installments, classification_feedback — none of those are
# demo-seeded content, and wiping them would break login / the audit trail /
# real usage you were testing manually.
DEMO_COLLECTIONS = [
    "invoices", "journal_entries", "client_invoices", "assets",
    "chartes_projet", "phases", "livrables", "lignes_budget",
    "feuilles_de_route", "risques", "budget_plan_entries",
    # Derived from the collections above — stale/inconsistent once those are
    # wiped, not demo content in their own right, so cleared alongside them.
    "audit_snapshots", "notifications",
]

# Re-run in this order: seed_projects before seed_risks/seed_roadmap (both
# reference the 3 demo projects), seed_demo before seed_budget_actuals
# (independent but seed_demo prints a fuller summary), generate_demo_invoice_pdfs
# last (needs the invoices seeded by the two before it to already exist).
SEED_SCRIPTS = [
    "seed_demo.py",
    "seed_budget_actuals.py",
    "seed_projects.py",
    "seed_risks.py",
    "seed_roadmap.py",
    "generate_demo_invoice_pdfs.py",
]

UPLOAD_DIR = ROOT / "data" / "uploads"
SEED_UPLOAD_DIR = UPLOAD_DIR / "seed"
EMAIL_OUTBOX_DIR = ROOT / "data" / "email_outbox"


def _clear_local_artifacts(dry_run: bool) -> None:
    non_seed_pdfs = sorted(p for p in UPLOAD_DIR.glob("*.pdf") if p.is_file())
    # data/uploads/seed/ must be cleared too, not just the top-level dir:
    # generate_demo_invoice_pdfs.py names files after each invoice's Mongo
    # _id, which is freshly generated by seed_demo.py/seed_budget_actuals.py
    # every reset — leaving the old files behind orphans them permanently
    # (verified: a first version of this script without this line left 102
    # stale PDFs in seed/ after a single reset cycle).
    seed_pdfs = sorted(p for p in SEED_UPLOAD_DIR.glob("*.pdf") if p.is_file())
    email_files = sorted(p for p in EMAIL_OUTBOX_DIR.glob("*") if p.is_file())

    print(f"\n[local files] {len(non_seed_pdfs)} orphan upload(s) in {UPLOAD_DIR}/, "
          f"{len(seed_pdfs)} in {SEED_UPLOAD_DIR}/ (regenerated by generate_demo_invoice_pdfs.py), "
          f"{len(email_files)} file(s) in {EMAIL_OUTBOX_DIR}/")
    if dry_run:
        return
    for p in non_seed_pdfs + seed_pdfs + email_files:
        p.unlink()


async def _clear_collections(dry_run: bool) -> None:
    if not await init_beanie():
        print("MONGODB_URI non défini ou connexion impossible — abandon.")
        sys.exit(1)

    db = _get_db()
    print("[mongo] collections to clear:")
    for name in DEMO_COLLECTIONS:
        count = db[name].count_documents({})
        print(f"  {name:22} {count} document(s)")
        if not dry_run and count:
            db[name].delete_many({})

    await close_mongodb()


def _reseed() -> None:
    for script in SEED_SCRIPTS:
        print(f"\n=== {script} ===")
        subprocess.run([sys.executable, str(ROOT / "scripts" / script)], check=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yes", action="store_true", help="actually clear + reseed (required to do anything)")
    parser.add_argument("--dry-run", action="store_true", help="show what would be cleared, no writes")
    args = parser.parse_args()

    if not args.yes and not args.dry_run:
        parser.error("pass --yes to actually reset, or --dry-run to preview")

    dry_run = args.dry_run and not args.yes

    _clear_local_artifacts(dry_run)
    asyncio.run(_clear_collections(dry_run))

    if dry_run:
        print("\n--dry-run: nothing was cleared, seeders not run.")
        return

    print("\n[reseed] running seeders in order…")
    _reseed()
    print("\nDone — demo data reset to a clean state.")


if __name__ == "__main__":
    main()
